# Generated by Django 5.1.7 on 2025-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcategory",
            name="category",
            field=models.CharField(
                choices=[
                    ("admission", "Admission Fee"),
                    ("application", "Application Fee"),
                    ("tuition", "Tuition Fee"),
                    ("uniform", "Uniform"),
                    ("books", "Books"),
                    ("id_card", "ID Card"),
                    ("computer_lab", "Computer Lab Training"),
                    ("competitive", "Competitive Classes"),
                    ("hostel", "Hostel Fee"),
                    ("winter_clothes", "Winter Clothes"),
                    ("transport", "Transport"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
