[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[start]
cmd = 'source /opt/venv/bin/activate && gunicorn school_website.wsgi:application --bind 0.0.0.0:$PORT' 