[phases.setup]
nixPkgs = [
    'python311',
    'python311Packages.pip',
    'python311Packages.virtualenv',
    'pango',
    'libffi',
    'cairo',
    'gobject-introspection',
    'libpng',
    'gdk-pixbuf',
    'freetype',
    'fontconfig',
    'harfbuzz',
    'fribidi',
    'libxml2',
    'libxslt',
    'libjpeg',
    'libtiff',
    'libwebp',
    'zlib',
    'brotli',
    'woff2',
    'libunwind',
    'glib',
    'gobject-introspection',
    'pkg-config',
    'gobject-introspection-unwrapped',
    'gobject-introspection-unwrapped.dev'
]

[phases.install]
cmds = [
    'export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/nix/store/*/lib/pkgconfig',
    'export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/nix/store/*/lib:/nix/store/*/lib64',
    'export GI_TYPELIB_PATH=/usr/lib/girepository-1.0:/nix/store/*/lib/girepository-1.0:/nix/store/*/lib64/girepository-1.0',
    'export LIBRARY_PATH=/usr/lib:/usr/local/lib:/nix/store/*/lib:/nix/store/*/lib64',
    'export C_INCLUDE_PATH=/nix/store/*/include',
    'export CPLUS_INCLUDE_PATH=/nix/store/*/include',
    'export LIBRARY_PATH=/nix/store/*/lib:/nix/store/*/lib64',
    'export LD_LIBRARY_PATH=/nix/store/*/lib:/nix/store/*/lib64',
    'export PKG_CONFIG_PATH=/nix/store/*/lib/pkgconfig',
    'export GI_TYPELIB_PATH=/nix/store/*/lib/girepository-1.0:/nix/store/*/lib64/girepository-1.0',
    'export LD_LIBRARY_PATH=/nix/store/*/lib:/nix/store/*/lib64:/nix/store/*/lib/gobject-introspection',
    'export GI_TYPELIB_PATH=/nix/store/*/lib/girepository-1.0:/nix/store/*/lib64/girepository-1.0:/nix/store/*/lib/gobject-introspection/girepository-1.0',
    'export PKG_CONFIG_PATH=/nix/store/*/lib/pkgconfig:/nix/store/*/lib/gobject-introspection/pkgconfig',
    'export PATH=/nix/store/*/bin:/nix/store/*/lib/gobject-introspection:$PATH',
    'mkdir -p /usr/lib',
    'echo "Setting up GObject libraries..."',
    'GLIB_PATH=$(pkg-config --variable=libdir gobject-2.0)',
    'if [ -z "$GLIB_PATH" ]; then echo "Error: Could not find GObject library path"; exit 1; fi',
    'echo "Found GObject library path: $GLIB_PATH"',
    'GOBJECT_SO="$GLIB_PATH/libgobject-2.0.so"',
    'if [ ! -f "$GOBJECT_SO" ]; then echo "Error: GObject library not found at $GOBJECT_SO"; exit 1; fi',
    'echo "Found GObject library at: $GOBJECT_SO"',
    'ln -sf "$GOBJECT_SO" /usr/lib/libgobject-2.0-0.so',
    'ln -sf "$GOBJECT_SO" /usr/lib/libgobject-2.0.so',
    'ln -sf "$GOBJECT_SO" /usr/lib/libgobject-2.0.so.0',
    'ldconfig'
] 