[phases.setup]
nixPkgs = [
    'python311',
    'python311Packages.pip',
    'python311Packages.virtualenv',
    'pango',
    'libffi',
    'cairo',
    'gobject-introspection',
    'libpng',
    'gdk-pixbuf',
    'freetype',
    'fontconfig',
    'harfbuzz',
    'fribidi',
    'libxml2',
    'libxslt',
    'libjpeg',
    'libtiff',
    'libwebp',
    'zlib',
    'brotli',
    'woff2',
    'libunwind',
    'glib',
    'gobject-introspection',
    'pkg-config',
    'libgobject'
]

[phases.install]
cmds = [
    'export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/nix/store/*/lib/pkgconfig',
    'export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/nix/store/*/lib',
    'export GI_TYPELIB_PATH=/usr/lib/girepository-1.0:/nix/store/*/lib/girepository-1.0',
    'export LIBRARY_PATH=/usr/lib:/usr/local/lib:/nix/store/*/lib',
    'export C_INCLUDE_PATH=/usr/include:/usr/local/include:/nix/store/*/include',
    'export CPLUS_INCLUDE_PATH=/usr/include:/usr/local/include:/nix/store/*/include',
    'export CPATH=/usr/include:/usr/local/include:/nix/store/*/include'
] 