[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = [
    'source /opt/venv/bin/activate',
    'python manage.py collectstatic --noinput',
]

[start]
cmd = '''
source /opt/venv/bin/activate
echo "Waiting for PostgreSQL to start..."
while ! pg_isready -h $PGHOST -p $PGPORT -U $PGUSER; do
    sleep 1
done
echo "PostgreSQL is ready!"
python setup_db.py && gunicorn school_website.wsgi:application --bind 0.0.0.0:$PORT
''' 